# Generated by Django 5.1b1 on 2024-07-07 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.URLField()),
                ('icon', models.ImageField(upload_to='networks/')),
                ('text', models.CharField(max_length=15)),
            ],
        ),
    ]
