# Generated by Django 5.1b1 on 2024-07-07 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_networks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='icon',
            field=models.TextField(max_length=18),
        ),
    ]
