# Generated by Django 5.1b1 on 2024-07-07 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_blog_icon_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_icon_3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.URLField()),
                ('icon', models.TextField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='blog_icon_2',
            name='icon',
            field=models.TextField(max_length=25),
        ),
    ]
