# Generated by Django 5.1b1 on 2024-07-07 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_blog_icon_3_alter_blog_icon_2_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_icon_3',
            name='text',
            field=models.CharField(default=1, max_length=18),
            preserve_default=False,
        ),
    ]
